before_install:
  - gem update --system
  - gem install bundler
install:
  - bundle install

bundler_args: --no-deployment --jobs 3 --retry 3

cache: bundler

env:
  global:
    - JRUBY_OPTS="-Xcli.debug=true --debug"

language: ruby
sudo: false

rvm:
  # latest versions on travis-ci as of 2018.09.04
  - jruby-9.1.9.0
  - ruby-2.3.7
  - ruby-2.4.4
  - ruby-2.5.1
  - jruby-head
  - ruby-head

gemfile:
- gemfiles/rails_4_2.gemfile
- gemfiles/rails_5_0.gemfile
- gemfiles/rails_5_1.gemfile
- gemfiles/rails_5_2.gemfile

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true
  exclude:
    # ruby-2.3.7 tests on all versions
    # ruby-2.4.4 tests on all versions
    # ruby-2.5.1 tests on all versions
    # jruby-9.1.9.0 only tests on rails 5.1+
    - rvm: jruby-9.1.9.0
      gemfile: gemfiles/rails_5_0.gemfile
    # jruby-head only tests on rails 5.2+
    - rvm: jruby-head
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/rails_5_1.gemfile
    # ruby-head only tests on rails 5.2+
    - rvm: ruby-head
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_5_1.gemfile
